Hublot Website configuring theme with MUI
Hublot-Tech/hublot-app pull request #11
Opened 2024-02-25 11:38 UTC by latioms

## Rapport detaille des accomplis :
- Intégration de MUI dans le projet web partie frontend :
  - Installation des librairies concernées et mise a jour auto des packages
  - Ajout des composants MUI dans une page test
- Élaboration des hooks et des helpers : 
  - Themecontextprovider de fournir un contexte de thème pour l'application, en fonction des préférences de l'utilisateur ou du thème système, et de mettre à jour le thème en conséquence.
  - Le rôle de useApplicationConfigs est de fournir un accès au contexte des configurations de l'application, y compris le thème actuel et une fonction pour changer de thème. Il détecte également les changements dans le thème système et les reflète dans l'application.
- Configuration du theme :
  - Configuration basique (au pif, vu qu'aucune maquette n'est prête pour l'app web) des couleur primaire et secondaire pour l'app. : 
  * Light mode : 
    - __color_primary = '#FFC000'
    - __color_neutral = '#FFFFFF'
    - __color_text = '#0A1128'
   * Dark mode : 
    - __dark_color_primary = '#0A1128'
    - __dark_color_neutral = '#646464'
    - __dark_color_text = '#FFFFFF'

2024-02-27 23:34 UTC, Marcjazz requested changes
Je pense que c'est du bon travail mais le code n'est pas tres bien formaté

2024-02-29 07:51 UTC, latioms commented
OK @Marcjazz  comment devrait je le formater ?
Et a quel niveau exactement ?

2024-02-29 07:53 UTC, latioms commented
Tu peix indexer les fichiers concernees en les commentant stp ?

2024-03-01 08:29 UTC, Marcjazz commented
> Tu peix indexer les fichiers concernees en les commentant stp ?

c'est surtout dans les fichier que tu as toi meme cree

2024-03-01 09:14 UTC, latioms commented
oK JUSTEMENT  quels fichiers ? ou bien tous ? va dans les files changed et commente les fichiers concernees stp

2024-03-07 05:27 UTC, Marcjazz commented
> oK JUSTEMENT quels fichiers ? ou bien tous ? va dans les files changed et commente les fichiers concernees stp

J'ai configuré un formateur donc maintenant tu vas juste taper la commande suivante à la racine du project web
`npm run format`

2024-03-24 07:22 UTC, Marcjazz approved these changes

2024-03-24 07:27 UTC, merged