Feature server setup docs
Hublot-Tech/hublot-app pull request #14
Opened 2024-03-03 00:12 UTC by francsteves

2024-03-07 04:55 UTC, Marcjazz commented
@latioms utilise la commande `npm run format` a la racine du server pour format ton code

2024-03-07 05:12 UTC, Marcjazz requested changes

2024-03-07 05:12 UTC, Marcjazz commented on server/src/Users/dto/users.dto.ts
> +    @IsNotEmpty({ message: 'Fullname is required' })
Pourquoi pas `@IsString()`
Ne te casse pas trop pour les messages, les messages par defaut sont meilleurs
Enlerve les duplicatats

2024-03-09 10:55 UTC, francsteves commented on server/src/app.controller.ts
> -    return this.appService.getHello();
Hello dans ce cas pas de message si on lance le base url de l'api

2024-03-09 11:38 UTC, Marcjazz commented on server/src/app.controller.ts
> -    return this.appService.getHello();
change just le message pas toute la fonction

2024-03-09 20:09 UTC, Marcjazz requested changes

2024-03-09 20:09 UTC, Marcjazz commented on server/src/Users/services/users.services.ts
> +  findAll(): Promise<UserDto[]> {
cette method retourne GetAllUserDto

2024-03-09 20:09 UTC, Marcjazz commented on server/src/Users/services/users.services.ts
> +  }
les deux metho ci ne retourne rien

2024-03-09 20:09 UTC, Marcjazz commented on server/src/app.controller.ts
> +@ApiTags('Hublot')
Ne met rien en parametre

2024-03-09 20:09 UTC, Marcjazz commented on server/src/Users/contollers/users.contollers.ts
> +    type: GetAllUserDto,
non pas ça quand meme

2024-03-09 20:09 UTC, Marcjazz commented on server/src/Users/dto/users.dto.ts
> +  @IsNotEmpty({ message: 'locale is required' })
utilise `@IsString()`

2024-03-09 20:09 UTC, Marcjazz commented on server/src/Users/dto/users.dto.ts
> +  @IsNotEmpty({ message: 'Email is required' })
`@IsEmail()` suffit

2024-03-09 20:09 UTC, Marcjazz commented on server/src/Users/dto/users.dto.ts
> +  @IsNotEmpty({ message: 'phoneNumber is required' })
utilise `@IsPhoneNumber()`

2024-03-09 20:09 UTC, Marcjazz commented on server/src/Users/dto/users.dto.ts
> +  @IsNotEmpty({ message: 'address is required' })
utilise `@IsString()` a la place

2024-03-24 07:27 UTC, Marcjazz approved these changes

2024-03-24 07:27 UTC, merged